### PR TITLE
V2.2.0

### PR DESCRIPTION
**Pull request by mark0n**

### CODE REVIEW

**Comment by aderbenev** [comment]
Thanks for the update, Martin! Our build environment is down for some maintenance so I cannot try it there right away, but that should be back up some time next week. Also, we'll be assembling a lab stand setup with various systems soon, including timing - and I'll put newest things to test there. No timeline for that part yet alas (weeks?)

**Comment by aderbenev** [comment]
From how many stars were to align for the test setup to become, I could've estimated "months" and not "weeks" and hence resort to a more prompt testing strategy. I have the practical usage put under a hood of a different project, but something I just tried myself at last is:

* git-buildpackage all succeeds in Debian 8 environment with base 3.15.3 - installation from epicsdeb.bnl.gov/debian
* Manual build is ok in the same environment
* Manual build fails on Debian 7.11 using base 3.14.12.3 - installation from epics.nsls2.bnl.gov/debian

Was building for MVME3100 on RTEMS 4.9 using https://github.com/epicsdeb/devlib2/commit/5c831ad74d06af0403938e8b1c1758a116183f42:

```
make -C O.RTEMS-mvme3100 -f ../Makefile TOP=../../.. T_A=RTEMS-mvme3100 install
make[3]: Entering directory `/tmp/timing-test/mrfioc2-package/evrMrmApp/src/O.RTEMS-mvme3100'

/usr/bin/powerpc-rtems4.9-g++ -B/usr/powerpc-rtems4.9/mvme3100/lib/ -specs bsp_specs -qrtems   -c   -mcpu=powerpc -msoft-float -D__ppc_generic              -DUNIX     -O2 -g -g  -Wall      -DMY_DO_BOOTP=NULL -DHAVE_MOTLOAD -DRTEMS_NETWORK_CONFIG_MBUF_SPACE=2048 -DRTEMS_NETWORK_CONFIG_CLUSTER_SPACE=5120     -MMD -I. -I../O.Common -I. -I../os/RTEMS -I../os/default -I.. -I../../../include/os/RTEMS -I../../../include -I../../../../devlib2/include/os/RTEMS -I../../../../devlib2/include -I/usr/lib/epics/include/os/RTEMS -I/usr/lib/epics/include -I/usr/lib/epics/include/os/RTEMS -I/usr/lib/epics/include -I/usr/lib/epics/include/os/RTEMS -I/usr/lib/epics/include -I/usr/lib/epics/include/os/RTEMS -I/usr/lib/epics/include       ../drvemInput.cpp 
In file included from ../../../include/mrfCommonIO.h:102,
                 from ../drvemInput.cpp:14:
../../../../devlib2/include/os/RTEMS/epicsMMIO.h:51: error: 'epicsUInt16' does not name a type
../../../../devlib2/include/os/RTEMS/epicsMMIO.h:59: error: 'epicsUInt32' does not name a type
make[3]: *** [drvemInput.o] Error 1
make[3]: Leaving directory `/tmp/timing-test/mrfioc2-package/evrMrmApp/src/O.RTEMS-mvme3100'
```

We are yet to shove it in the test environment and verify the actual function. Pardon the stunning promptness.

Also, I recall a recent discussion on tech-talk about plans to introduce external changes (PSI) to the code. Gotta deal with this new upstream before a newer comes...

**Comment by mark0n** [comment]
@aderbenev Debian 7 is not supported anymore (long-term support ended on 31 May 2018). Let's not worry about the build issue but rather spend our time moving to a newer release...

**Comment by aderbenev** [comment]
What we're doing with that right now is dropping it into a bowl with RTEMS 4.10 and EPICS7 to see what happens. The IOC looks operational but we need to test the entire setup function to be certain... plus the profile thing now. In a hindsight, it was not the best idea to mix many pieces together. I guess I'll just build this one along with other now-profile-enabled packages in our setup.

**Pull request merged**
